name = "jl_lambda_eval"
uuid = "1ade3078-c3e4-4b1c-a1bb-3fe08b7eec35"
authors = ["Ben Carver <bcarver2@gmu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "62d5dde6-af31-4731-be8d-9fc14fd3df40"

[targets]
test = ["Test"]
