name = "jl_lambda_eval"
uuid = "1ade3078-c3e4-4b1c-a1bb-3fe08b7eec35"
authors = ["Ben Carver <bcarver2@gmu.edu> and contributors"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1"

[extras]
Test = "62d5dde6-af31-4731-be8d-9fc14fd3df40"

[targets]
test = ["Test"]
